# starship.toml

# config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
[$directory](fg:sumi-ink-3 bg:carp-yellow)\
[](fg:carp-yellow bg:surimi-orange)\
[$container$rust$python$lua$docker_context$git_branch$git_status$hostname$jobs](fg:sumi-ink-3 bg:surimi-orange)\
[](fg:surimi-orange bg:peach-red)\
[$character](fg:sumi-ink-3 bg:peach-red)\
[](fg:peach-red)\
[ ](none)"""

add_newline = false
palette = "kanagawa"

[palettes.kanagawa]
peach-red = "#ff5d62"
carp-yellow = "#e6c384"
surimi-orange = "#ffa066"
sumi-ink-3 = "#1f1f28"

[character]
format = "$symbol"
success_symbol = ' \$ '
error_symbol = " # "
vimcmd_symbol = " N "
vimcmd_replace_one_symbol = " R "
vimcmd_replace_symbol = " R "
vimcmd_visual_symbol = " V "

[directory]
format = " $path ($read_only)"
read_only = "󰌾 "
truncation_symbol = ""
truncation_length = 2
truncate_to_repo = false

[git_branch]
symbol = " "
format = " $symbol$branch "

[git_status]
style = "black bg:surimi-orange"
format = '([$all_status$ahead_behind]($style) )'

[python]
format = " $symbol($virtualenv )($version )"
symbol = " "

[rust]
format = " $symbol($version )"
symbol = " "

[lua]
format = " $symbol($version )"
symbol = " "

[package]
symbol = '󰏗 '

[hostname]
format = " $ssh_symbol$hostname "
ssh_only = true
ssh_symbol = "󰣀 "

[container]
format = " $symbol$name "
symbol = " "

[docker_context]
symbol = " "
style = "black"
#style = "fg:#06969A"
format = "[$symbol]($style) $path"
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_extensions = ["Dockerfile"]

[jobs]
symbol = " "
style = "black"
#style = "red"
number_threshold = 1
format = "[$symbol]($style)"

