# keymap.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
[[manager.prepend_keymap]]
run = """shell 'zip -r "$0".zip $(basename "$0")' --interactive"""
on = ["u", "z"]
desc = "Zip hovered file/directory"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = "<Space>"
run = "toggle"
desc = "Toggle selection"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on  = "k"
run = "plugin arrow -1"

[[manager.prepend_keymap]]
on  = "j"
run = "plugin arrow 1"

[[manager.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[manager.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"
