# yazi.toml
#:$schema = "https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio = [3, 5, 9]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
linemode = "size"
show_hidden = true
show_symlink = false
sort_dir_first = true

[tasks]
micro_workers = 10
macro_workers = 10
bizarre_retry = 3
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false

[preview]
wrap = "no"                    # Disable wrapping for better text previews
tab_size = 2                   # Keep tab size small for better formatting
max_width = 960                # Good limit for the preview window width
max_height = 600               # Good limit for the preview window height
cache_dir = ""                 # Use Yazi/system default cache location
image_delay = 0                # Show image previews immediately
image_filter = "triangle"      # Not highest quality but faster
image_quality = 75             # Better image quality
ueberzug_scale = 1             # Keep image scale at default
ueberzug_offset = [0, 0, 0, 0] # No offset adjustments needed

[open]
prepend_rules = [
    { url = "*.rnote", use = "open" },
    { url = "*/", use = [
        "open",
        "edit",
    ] },
]

[plugin]
prepend_fetchers = [
    { url = "*", run = "git", group = "git" },
    { url = "*/", run = "git", group = "git" },
]
