# yazi.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [3, 5, 9]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
linemode = "size"
show_hidden = true
show_symlink = false
sort_dir_first = true

[tasks]
micro_workers = 10
macro_workers = 10
bizarre_retry = 3
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false

[preview]
wrap = "no"  # Disable wrapping for better text previews
tab_size = 2  # Keep tab size small for better formatting
max_width = 600  # Good limit for the preview window width
max_height = 900  # Good limit for the preview window height
cache_dir = ""  # Disable caching for faster previews
image_delay = 0  # Slightly increased delay to reduce flickering
image_filter = "lanczos3"  # Higher quality image scaling
image_quality = 90  # Better image quality
sixel_fraction = 20  # Better quality SIXEL previews
ueberzug_scale = 1  # Keep image scale at default
ueberzug_offset = [0, 0, 0, 0]  # No offset adjustments needed

[open]
prepend_rules = [
    {name = "*.rnote", use = "open"},
    {name = "*/", use = ["open", "edit"]},
]
