# Remap prefix from 'C-b' to 'C-' unbind C-b
unbind C-b
set -g prefix C-Space
bind C-a send-prefix

# Reload config source
unbind r
bind r source-file ~/.config/tmux/tmux.conf; display "tmux loaded"

# Terminal type for tmux
set -g default-terminal "tmux-256color"
# Force true color support
set -ga terminal-overrides ",*:Tc"
# Allow applications to use italics and underlines
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=brightblue

#General
set -g status-position bottom  # Status position
set -g set-clipboard on  # Use system clipboard
set -g escape-time 0  # Remove delay for exiting insert mode with ESC in Neovim
set -g mouse on  # Enable mouse control
set -g status-interval 5  # Status update interval (default: 15)
set -g detach-on-destroy off  # Don't close tmux when closing session
set -s exit-empty off  # Don't close tmux if no active sessions
set -g history-limit 1000000  # Scrollback lines number (default: 2000)
set -g allow-passthrough on  # Allow programs in the pane to bypass tmux (e.g. for image preview)
set -g display-time 4000  # Show message longer

# Window and pane numbering to start from 1 (default: 0)
set -g base-index 1
setw -g pane-base-index 1
# Automatically renumber windows when one is closed
set -g renumber-windows on
# Don't rename windows automatically
set -g allow-rename off
setw -g automatic-rename off
# Synchronize input
bind b set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# Create new window
bind c new-window -c "#{pane_current_path}"
# Name new window when create
bind C command-prompt -p "New window name: " "new-window -n '%%'"
# Joih Pane to current Window
bind   @ choose-window 'join-pane -h -s "%%"'
bind C-@ choose-window 'join-pane    -s "%%"'

# Split vertically
unbind %
bind | split-window -h -c "#{pane_current_path}"
# Split horizontally
unbind \"
bind \\ split-window -v -c "#{pane_current_path}"

# vi Mode
setw -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel
# Paste yanked text with "Prefix + P" ("Prefix + p" goes to previous window)
bind P paste-buffer
# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Resize panes
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 6
bind h resize-pane -L 5
# Maximize pane
unbind z
bind m resize-pane -Z 

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'
# List of plugins
set -g @plugin 'christoomey/vim-tmux-navigator'  # Enable navigating between nvim and tmux
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'  # Persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum'  # Automatically saves sessions every 15 minutes

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
#set -g @continuum-restore 'on'

#set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
#set -g @vim_navigator_mapping_right "C-Right C-l"
#set -g @vim_navigator_mapping_up "C-k"
#set -g @vim_navigator_mapping_down "C-j"
#set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
