## If you come from bash you might have to change your $PATH.
#export PATH=$HOME/bin:/usr/local/bin:$PATH

## Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

## Theme
ZSH_THEME="nicoulaj"

## Prompt
RPROMPT="%D{%L:%M:%S}"

## Disable auto-setting terminal title for tmux pane
DISABLE_AUTO_TITLE="true"

## Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

## Large repo fast status check
DISABLE_UNTRACKED_FILES_DIRTY="true"

## History with time
HIST_FORMAT="'%Y-%m-%d %T:'$(echo -e '\t')"
alias history="fc -t "$HIST_FORMAT" -il 1"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

## User configuration

## GNUPG encryption settings
GPG_TTY=$(tty)

## Tell the pinentry program to use the nice, full-screen pinentry program:
export PINENTRY_USER_DATA="USE_CURSES=1"

## Enable syntax highlithing
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

## mc cyrillic issue solved (:
export LC_ALL='en_US.UTF-8'

# Disable mc use of the concurrent shel (fast load)
alias mc='mc --nosubshell'

## Nvim alias
alias n="nvim"
alias vim="nvim"
alias vi="nvim"

## Vi editing mode
#bindkey -v
#export KEYTIMEOUT=1
#bindkey '^P' up-history
#bindkey '^N' down-history
#bindkey '^?' backward-delete-char
#bindkey '^h' backward-delete-char
#bindkey '^w' backward-kill-word
#bindkey '^r' history-incremental-search-backward

## Refresh shell
alias reload='. ~/.zshrc'

## ls aliases
alias ls='ls -GCF' # color, multicolumns, filetypes
alias la='ls -A' # all files except . and .. (almost all)
alias l.='ls -d .*' # only hidden fil
alias ll='ls -lah' # long list alphabetical sort
alias lt='ls -lahtr' # long list oldest first sort
alias lz='ls -lahS' # long list largest first
alias l='ls -dlh' # long dir info

## Interactive by default
alias rm='rm -i'
alias mv='mv -i'

## Lock computer
alias lock='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'

## myip, FQDN
alias myip="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias fqdn="host `hostname`"

## rsync
alias rsynk="rsync -avzhP"

## Reattach to session or create new
alias tt="tmux attach -t base || tmux new -s base"
